parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        charset: utf8
        url: '%env(DATABASE_URL)%'
        schema_filter: ~^(?!sessions).+$~
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            FixxxSchuldhulp:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'GemeenteAmsterdam\FixxxSchuldhulp\Entity'
                alias: FixxxSchuldhulp
        dql:
            string_functions:
              FULLTEXTSEARCH: GemeenteAmsterdam\FixxxSchuldhulp\Query\Functions\FullTextSearch
