doctrine:
  dbal:
    url: '%env(resolve:dburl:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
    wrapper_class: GemeenteAmsterdam\FixxxSchuldhulp\Doctrine\DynamicConnection
  orm:
    report_fields_where_declared: true
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: false
    enable_lazy_ghost_objects: true
    mappings:
      FixxxSchuldhulp:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'GemeenteAmsterdam\FixxxSchuldhulp\Entity'
        alias: FixxxSchuldhulp
    dql:
      string_functions:
        FULLTEXTSEARCH: GemeenteAmsterdam\FixxxSchuldhulp\Query\Functions\FullTextSearch
        LEVENSHTEIN: GemeenteAmsterdam\FixxxSchuldhulp\Query\Functions\Levenshtein

when@acceptance:
  doctrine:
    orm:
      metadata_cache_driver:
        type: service
        id: doctrine.system_cache_provider
      query_cache_driver:
        type: service
        id: doctrine.system_cache_provider
      result_cache_driver:
        type: service
        id: doctrine.result_cache_provider

  services:
    doctrine.result_cache_provider:
      class: Symfony\Component\Cache\DoctrineProvider
      public: false
      arguments:
        - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
      class: Symfony\Component\Cache\DoctrineProvider
      public: false
      arguments:
        - '@doctrine.system_cache_pool'

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
