monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - gebruiker
    handlers:
        nested:
            type: stream
            path: php://stderr
            level: error
            formatter: monolog.formatter.json
        csp_violations: # Add a handler for the csp_violations channel
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%-csp_violations.log"
            level: notice
            channels: [ "csp_violations" ]
        gebruiker:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [gebruiker]

