twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'forms.html.twig'
    globals:
        app_version: '@GemeenteAmsterdam\FixxxSchuldhulp\Service\ApplicationVersion'
        featureflag_herfinanciering: '%featureflag_herfinanciering%'