framework:
  workflows:
    dossier_flow:
      type: state_machine
      marking_store:
        type: method
        property: status
      supports:
        - GemeenteAmsterdam\FixxxSchuldhulp\Entity\Dossier
      places:
        - bezig_madi
        - compleet_madi
        - gecontroleerd_madi
        - verzonden_madi
        - compleet_gka
        - dossier_gecontroleerd_gka
        - afgesloten_gka
      transitions:
        opgevoerd_madi: { from: [bezig_madi], to: compleet_madi }
        goedkeuren_madi: { from: [compleet_madi], to: gecontroleerd_madi }
        afkeuren_madi: { from: [compleet_madi, gecontroleerd_madi], to: bezig_madi }
        verzenden_madi: { from: [gecontroleerd_madi], to: verzonden_madi }
        gestart_gka: { from: [verzonden_madi], to: compleet_gka }
        goedkeuren_dossier_gka: { from: [compleet_gka], to: dossier_gecontroleerd_gka }
        afkeuren_dossier_gka: { from: [compleet_gka], to: bezig_madi }
        afsluiten_gka: { from: dossier_gecontroleerd_gka, to: afgesloten_gka }
