trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'

pr: none

pool: Selfhosted Azure Devops Agents

steps:
  - bash: |
      az pipelines run --project 'salmagundi' --id 3193 --branch $(Build.SourceBranch) --detect true
    displayName: 'Trigger Schulddossier application pipeline'
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)