FROM nginx:stable-alpine

COPY certificates/adp_rootca.crt /usr/local/share/ca-certificates/adp_rootca.crt
RUN update-ca-certificates --fresh

RUN apk update && apk upgrade

RUN apk add \
    yarn

COPY docker-nginx/default.template /tmp/default.template
COPY --chown=nginx ./public /var/www/public

COPY --chown=nginx ./package.json /var/www/package.json
COPY --chown=nginx ./yarn.lock /var/www/yarn.lock

WORKDIR /var/www

RUN yarn --ignore-scripts --ignore-platform
RUN yarn run postinstall

RUN chown -R nginx ./public/vendor

CMD envsubst '$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'

EXPOSE 80
