version: '3.5'
services:
  schulddossier-phpfpm:
    build:
      context: .
      dockerfile: Dockerfile_phpfpm
    environment:
      - TZ=Europe/Amsterdam
    image: ${REGISTRY:-kind-registry:5000}/${REPOSITORY:-salmagundi/schulddossier-phpfpm}:${VERSION:-latest}
    
  schulddossier-nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    environment:
      - TZ=Europe/Amsterdam
    image: ${REGISTRY:-kind-registry:5000}/${REPOSITORY:-salmagundi/schulddossier-nginx}:${VERSION:-latest}
    depends_on:
      - schulddossier-phpfpm