FROM nginx:stable-alpine

COPY certificates/adp_rootca.crt /usr/local/share/ca-certificates/adp_rootca.crt
RUN update-ca-certificates --fresh

RUN apk update && apk upgrade

COPY docker-nginx/default.template /tmp/default.template

RUN envsubst '$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf

RUN mkdir /var/www && \
    chown -R nginx:nginx /var/www && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /etc/nginx && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

COPY --chown=nginx ./public /var/www/public

USER nginx
WORKDIR /var/www

CMD exec nginx -g 'daemon off;'

EXPOSE 80
