version: '3.2'
services:
  database_dev:
    image: postgres:9.5.11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: schuldhulp
      POSTGRES_DB: schuldhulp

  web_dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - .:/srv/app:rw,cached
      - /srv/app/var/
      - /srv/app/components/
#      - type: bind
#        source: .
#        target: /srv/app
#      - type: bind
#        source: ./config
#        target: /srv/app/config
##      - type: bind
##        source: ./public
##        target: /srv/app/public
#      - type: bind
#        source: ./src
#        target: /srv/app/src
##      - type: bind
##        source: ./doc
##        target: /srv/app/doc
##      - type: bind
##        source: ./translations
##        target: /srv/app/translations
#      - type: bind
#        source: ./templates
#        target: /srv/app/templates
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "schuldhulp-ft.sociaal.amsterdam.nl:10.16.136.56"
      - "host.docker.internal:host-gateway"
    links:
      - database_dev
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=secret
      - DATABASE_URL=pgsql://schuldhulp:insecure@database_dev:5432/schuldhulp
      - SWIFT_AUTH_URL=
      - SWIFT_REGION=
      - SWIFT_USER_NAME=
      - SWIFT_USER_DOMAIN_ID=
      - SWIFT_USER_PASSWORD=
      - SWIFT_PROJECT_ID=
      - SWIFT_CONTAINER_PREFIX=
      - SWIFT_TEMP_URL_KEY=
      - SWIFT_EXTERNAL_DOMAIN=
      - APP_NOTIFICATIE_FROM=tester@test.com
      - THUMBNAILSERVICE_URL=https://thumbnail.service/
      - IAM_LOGOUT_URL=http://host.docker.internal:8080/auth/realms/ams/protocol/openid-connect/logout
      - IAM_CLIENT_ID=schuld
      - IAM_CLIENT_SECRET=TmqRJUQ5FBEzjpUxPOcGkGM4wR7OTRwj
      - IAM_URL=http://host.docker.internal:8080/auth/realms/ams
      - ALLEGRO_ENDPOINT=https://schuldhulp-ft.sociaal.amsterdam.nl:8084/SOAP
      - ALLEGRO_ONBEKENDE_SCHULDEISER=2450232
      - MAILER_DSN=smtp://localhost

  mariadb:
    image: mariadb
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    volumes:
     - ./keycloak_realms:/opt/jboss/keycloak/imports
#     - ./keycloak_theme:/opt/jboss/keycloak/themes
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/ams.json"
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
      - "9990:9990"
volumes:
  mysql_data:
    driver: local