name: schulddossier-phpfpm

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

labels:
  app: schulddossier-phpfpm

network:
  allow-ingress:
    selector: app == 'schulddossier-phpfpm'
    ingress:
      - action: Allow
    egress:
      - action: Allow

deployments:
  schulddossier-phpfpm:
    image:
      repository: salmagundi/schulddossier-phpfpm
    selectorLabels:
      app: schulddossier-phpfpm

    containers:
      - name: main
        ports:
          - port: 8080
            name: http
  schulddossier-nginx:
    image:
      repository: salmagundi/schulddossier-nginx
    selectorLabels:
      app: schulddossier-nginx
    containers:
      - name: main
        ports:
          - port: 8080
            name: http

services:
  schulddossier-phpfpm:
    selector:
      app: schulddossier-phpfpm
    ports:
      - port: 8080
        targetPort: http
  schulddossier-nginx:
    selector:
      app: schulddossier-nginx
    ports:
      - port: 8080
        targetPort: http

ingress:
  schulddossier-nginx-internal:
    className: nginx-internal
    paths:
      - path: /
        service: schulddossier-nginx
        port: 8080