name: schulddossier
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: schulddossier

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'schulddossier'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app:
    enableWorkloadIdentity: true

secrets:
  certificate:
    type: keyvault
    tls: schulddossier
  my-vault-secrets:
    type: keyvault
    secrets:
      - iam-client-id
      - iam-client-realm
      - iam-client-secret
      - iam-logout-url
      - iam-url
      - mailer-dsn

deployments:
  schulddossier-phpfpm:
    env:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: insecure
      DATABASE_URL: pgsql://schulddossier-app-o:temporary@schulddossier-o-o354tdmk.postgres.database.azure.com:5432/main?serverVersion=13&charset=utf8
      ALLEGRO_ENDPOINT: https://schuldhulp-ft.sociaal.amsterdam.nl:8084/SOAP
      ALLEGRO_ONBEKENDE_SCHULDEISER: "0"
    image:
      repository: salmagundi/schulddossier-phpfpm
    securityContext:
      runAsUser: 82 #TODO: maybe this is a system user
    selectorLabels:
      component: phpfpm
    serviceAccount: app
    containers:
      - name: main
        ports:
          - port: 9000
            name: http
        secrets:
          - my-vault-secrets
        volumes:
          - name: cache
            mountPath: /var/www/var/cache
          - name: logs
            mountPath: /var/www/var/log
          - name: lock
            mountPath: /run/lock
          - name: tmp
            mountPath: /tmp
          - name: localworkingstorage
            mountPath: /var/www/public/localworkingstorage
    volumes:
      - name: cache
        spec:
          emptyDir: { }
      - name: logs
        spec:
          emptyDir: { }
      - name: lock
        spec:
          emptyDir: { }
      - name: tmp
        spec:
          emptyDir: { }
      - name: localworkingstorage
        spec:
          emptyDir: { }

  schulddossier-nginx:
    image:
      repository: salmagundi/schulddossier-nginx
    securityContext:
      runAsUser: 101
    selectorLabels:
      component: nginx
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        volumes:
          - name: logs
            mountPath: /var/log/nginx
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
          - name: localworkingstorage
            mountPath: /var/www/public/localworkingstorage
    volumes:
      - name: logs
        spec:
          emptyDir: { }
      - name: run
        spec:
          emptyDir: { }
      - name: cache
        spec:
          emptyDir: { }
      - name: localworkingstorage
        spec:
          emptyDir: { }

services:
  schulddossier-phpfpm:
    selector:
      component: phpfpm
    ports:
      - port: 9000
        targetPort: http
  schulddossier-nginx:
    selector:
      component: nginx
    ports:
      - port: 8080
        targetPort: http

ingress:
  schulddossier-nginx-internal:
    className: nginx-internal
    paths:
      - path: /
        prefix: Prefix
        service: schulddossier-nginx
        port: 8080
    tls:
      secretNameOverride: schulddossier

jobs:
  migrate:
    ttlSecondsAfterFinished: 100
    image:
      repository: salmagundi/schulddossier-phpfpm
    annotations:
      helm.sh/hook: post-install,post-upgrade
    containers:
      - name: main
        secrets:
          - my-vault-secrets
        volumes:
          - name: cache
            mountPath: /var/www/var/cache
          - name: logs
            mountPath: /var/www/var/log
          - name: lock
            mountPath: /run/lock
          - name: tmp
            mountPath: /tmp
        command: ["php", "bin/console", "doc:mig:mig"]
        env:
          APP_ENV: dev
          APP_DEBUG: 1
          APP_SECRET: insecure
          DATABASE_URL: pgsql://schulddossier-app-o:temporary@schulddossier-o-o354tdmk.postgres.database.azure.com:5432/main?serverVersion=13&charset=utf8
    backoffLimit: 2

    volumes:
      - name: cache
        spec:
          emptyDir: {}
      - name: logs
        spec:
          emptyDir: {}
      - name: lock
        spec:
          emptyDir: {}
      - name: tmp
        spec:
          emptyDir: {}