name: schulddossier
tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

labels:
  app: schulddossier

image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  tag: latest

network:
  allow-ingress:
    selector: app == 'schulddossier'
    ingress:
      - action: Allow
    egress:
      - action: Allow

serviceAccount: app
serviceAccounts:
  app: {}

secrets:
  certificate:
    type: keyvault
    tls: schulddossier

deployments:
  schulddossier-phpfpm:
    env:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: insecure
      DATABASE_URL: pgsql://adus-app-o:temporary@schulddossier-o-o354tdmk.postgres.database.azure.com:5432/main?serverVersion=13&charset=utf8
    image:
      repository: salmagundi/schulddossier-phpfpm
    securityContext:
      runAsUser: 82 #TODO: maybe this is a system user
    selectorLabels:
      component: phpfpm
    containers:
      - name: main
        ports:
          - port: 9000
            name: http
        volumes:
          - name: cache
            mountPath: /var/www/var/cache
          - name: logs
            mountPath: /var/www/var/log
          - name: lock
            mountPath: /run/lock
          - name: tmp
            mountPath: /tmp
    volumes:
      - name: cache
        spec:
          emptyDir: { }
      - name: logs
        spec:
          emptyDir: { }
      - name: lock
        spec:
          emptyDir: { }
      - name: tmp
        spec:
          emptyDir: { }
  schulddossier-nginx:
    image:
      repository: salmagundi/schulddossier-nginx
    securityContext:
      runAsUser: 101
    selectorLabels:
      component: nginx
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        volumes:
          - name: logs
            mountPath: /var/log/nginx
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
    volumes:
      - name: logs
        spec:
          emptyDir: { }
      - name: run
        spec:
          emptyDir: { }
      - name: cache
        spec:
          emptyDir: { }

services:
  schulddossier-phpfpm:
    selector:
      component: phpfpm
    ports:
      - port: 9000
        targetPort: http
  schulddossier-nginx:
    selector:
      component: nginx
    ports:
      - port: 8080
        targetPort: http

ingress:
  schulddossier-nginx-internal:
    className: nginx-internal
    paths:
      - path: /
        prefix: Prefix
        service: schulddossier-nginx
        port: 8080
    tls:
      secretNameOverride: schulddossier
