name: schulddossier

trigger: none

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: azure-templates
      type: git
      name: salmagundi/azure-templates

extends:
  template: pipelines/aks/template.yaml@azure-templates
  parameters:
    name: schulddossier
    build:
      pool:
        name: ContainerBuilder
    dev:
      pool: salmagundi
      namespace: ns-ccc-salm-ont-01-schulddossier
      kubernetesServiceConnection: SCN-K8S-ns-ccc-salm-ont-01-schulddossier
    test:
      pool: salmagundi
      namespace: ns-ccc-salm-tst-01-schulddossier
      kubernetesServiceConnection: SCN-K8S-ns-ccc-salm-tst-01-schulddossier