#index:
#    path: /
#    controller: App\Controller\DefaultController::index

csp_report:
  path: /csp/report
  methods: [POST]
  defaults: { _controller: nelmio_security.csp_reporter_controller::indexAction }