parameters:
    swift_public_url: '%swift_external_domain%/localworkingstorage'

services:
    # Flysystem
    flysystem_openstack_adapter_dossier:
        class: League\Flysystem\Adapter\Local
        lazy: true
        arguments:
            - '%kernel.project_dir%/public/localworkingstorage/dossier/'
    flysystem_dossier:
        class: League\Flysystem\Filesystem
        lazy: true
        arguments:
            - '@flysystem_openstack_adapter_dossier'