

keyVaultName: schulddossier-o-o354tdmk

workloadIdentity: 276621e3-684f-4524-a0da-46dd07897d72

nodepool: cccsalmont01

host: schulddossier.salm-o.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-o-xxmtgnro7phka

deployments:
  schulddossier-phpfpm:
    autoscale:
      cpu: 70
      memory: 90
      min: 1
      max: 2