

keyVaultName: schulddossier-o-o354tdmk

workloadIdentity: f9a5e50d-9eaa-4d74-8561-8fbb8b2232a5

nodepool: cccsalmont01

host: schulddossier.salm-o.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-o-xxmtgnro7phka

deployments:
  schulddossier-phpfpm:
    autoscale:
      cpu: 70
      memory: 90
      min: 1
      max: 2