workloadIdentity: c456cfaa-88b8-489a-a74b-1074c9257e89

keyVaultName: schulddossier-t-izpkvmrb

nodepool: cccsalmtst01

host: schulddossier.salm-t.azure.amsterdam.nl

secrets:
  certificate:
    keyVaultName: shared-t-7ft3qruminlt6
  my-vault-secrets:
    keyVaultName: schulddossier-t-izpkvmrb

deployments:
  schulddossier-phpfpm:
    env:
      ENV: dev
      APP_SECRET: insecure
      APP_ENV: dev
      APP_DEBUG: 0
      DATABASE_URL: pgsql://schulddossier-app-t:temporary@schulddossier-t-izpkvmrb.postgres.database.azure.com:5432/main?serverVersion=13&charset=utf8
      ALLEGRO_ENDPOINT: "https://schuldhulp.sociaal.amsterdam.nl:8084/SOAP"
      APP_NOTIFICATIE_FROM: "noreply@amsterdam.nl"
      ALLEGRO_ONBEKENDE_SCHULDEISER: "2506424"
      APP_GKA_NOTIFICATIE_ADRES: "kredietbank.salmagundi@amsterdam.nl"
      SWIFT_AUTH_URL:
      SWIFT_REGION:
      SWIFT_USER_DOMAIN_ID:
      SWIFT_EXTERNAL_DOMAIN:
      SWIFT_USER_NAME:
      SWIFT_USER_PASSWORD:
      SWIFT_PROJECT_ID:
      SWIFT_CONTAINER_PREFIX:
      SWIFT_TEMP_URL_KEY:
      THUMBNAILSERVICE_URL:

      TRUSTED_PROXIES: "10.243.0.0/16"
      # IAM_CLIENT_ID: VAULTED
      # IAM_CLIENT_SECRET:VAULTED
      # IAM_URL: VAULTED
      # IAM_LOGOUT_URL: VAULTED
      FEATUREFLAG_HERFINANCIERING: "0"
    autoscale:
      cpu: 70
      memory: 90
      min: 1
      max: 2

jobs:
  migrate:
    ttlSecondsAfterFinished: 100
    image:
      repository: salmagundi/schulddossier-phpfpm
    annotations:
      helm.sh/hook: post-install,post-upgrade
    containers:
      - name: main
        volumes:
          - name: cache
            mountPath: /var/www/var/cache
          - name: logs
            mountPath: /var/www/var/log
          - name: tmp
            mountPath: /tmp
        command: ["php", "bin/console", "doc:mig:mig"]
        env:
          ENV: dev
          APP_SECRET: insecure
          APP_ENV: dev
          APP_DEBUG: 0
          DATABASE_URL: pgsql://schulddossier-app-t:temporary@schulddossier-t-izpkvmrb.postgres.database.azure.com:5432/main?serverVersion=13&charset=utf8
          ALLEGRO_ENDPOINT: "https://schuldhulp.sociaal.amsterdam.nl:8084/SOAP"
          APP_NOTIFICATIE_FROM: "noreply@amsterdam.nl"
          ALLEGRO_ONBEKENDE_SCHULDEISER: "2506424"
          APP_GKA_NOTIFICATIE_ADRES: "kredietbank.salmagundi@amsterdam.nl"
          SWIFT_AUTH_URL:
          SWIFT_REGION:
          SWIFT_USER_DOMAIN_ID:
          SWIFT_EXTERNAL_DOMAIN:
          SWIFT_USER_NAME:
          SWIFT_USER_PASSWORD:
          SWIFT_PROJECT_ID:
          SWIFT_CONTAINER_PREFIX:
          SWIFT_TEMP_URL_KEY:
          THUMBNAILSERVICE_URL:

          AZURE_SUBSCRIPTION_ID: ca66dbbd-4567-4bdb-aa01-bbf33dd9576a
          AZURE_RESOURCE_GROUP: schulddossier-t-rg
          AZURE_STORAGE_FILE_ACCOUNT: schulddossierdatatizpkvm
          AZURE_STORAGE_FILE_CONTAINER: data


          TRUSTED_PROXIES: "10.243.0.0/16"
          # IAM_CLIENT_ID: VAULTED
          # IAM_CLIENT_SECRET:VAULTED
          # IAM_URL: VAULTED
          # IAM_LOGOUT_URL: VAULTED
          FEATUREFLAG_HERFINANCIERING: "0"
    backoffLimit: 2

    volumes:
      - name: cache
        spec:
          emptyDir: {}
      - name: logs
        spec:
          emptyDir: {}
      - name: tmp
        spec:
          emptyDir: {}
